Add: Deus Ex hidden message
Loevland/UiTHack24 pull request #110
Opened 2024-02-12 11:51 UTC by mrtz-j

Draft

Closes #57

2024-02-12 11:53 UTC, Loevland commented
Ser at `challenge.yml` mangler, og er det meningen at det skal være 2 oppgaver i denne PRen?

2024-02-12 12:03 UTC, Loevland commented on Crypto/Deus-Ex/challenge.yml
> +value: 100
```suggestion
value: 500
```

2024-02-12 12:04 UTC, Loevland commented on Crypto/Deus-Ex/challenge.yml
> +type: standard
```suggestion
type: dynamic
extra:
    initial: 500
    decay: 50
    minimum: 100
```

2024-02-12 12:09 UTC, Loevland requested changes
Mangler det en oppgavetekst til oppgaven?
Skal teste oppgaven i kveld, men hvis det er steganografi som er brukt, og brukes for å løse oppgaven, så tror jeg `Misc` er en mer passende kategori (men dette kommer an på løsningen, som jeg ikke har testet ennå)

Ting som burde fikses:
- Oppdatere oppgavetabellen ytterst i repoet i README.md
- Bildet som linket til fra README.md eksisterer ikke
- Oppdatere `files:` feltet i `challenge.yml` til å referere til rett fil (refererer til `src/location.png` atm)
- Foreslåtte endringer i `challenge.yml`
- Mangler oppgavetekst?
- Fint hvis du har writeup på denne

2024-02-13 08:10 UTC, Loevland commented
@mrtz-j @as505 Har dokker sjekka at løsninga funke? Får ikke ut nokka flagg med å følge stegan i writeupen

2024-02-13 08:22 UTC, mrtz-j commented
> @mrtz-j @as505 Har dokker sjekka at løsninga funke? Får ikke ut nokka flagg med å følge stegan i writeupen

Fulgte dem ganske rettfrem igår og det fungerte.

2024-02-13 08:23 UTC, Loevland commented
> > @mrtz-j @as505 Har dokker sjekka at løsninga funke? Får ikke ut nokka flagg med å følge stegan i writeupen
> 
> Fulgte dem ganske rettfrem igår og det fungerte.

På samme bildet som ligg i repoet?

2024-02-13 08:25 UTC, mrtz-j commented
Jepp, `Jc_Denton`

![image](https://github.com/Loevland/UiTHack24/assets/14005567/59ace640-4d53-46ce-b6c6-d49518c8cef1)

2024-02-13 09:46 UTC, Loevland commented
Ser ut som om æ hadde en tidligere versjon av bildet lasta ned, som ikke hadde noe info i sæ 😅

2024-02-13 09:49 UTC, Loevland approved these changes

2024-02-13 09:49 UTC, merged