Geosint challenge
Loevland/UiTHack24 pull request #68
Opened 2023-10-26 16:50 UTC by Loevland

Closes #11

2023-10-30 15:12 UTC, mrtz-j commented
Er ikke denne litt for enkel ? Kunne kanskje brukt flere bilder for å gjøre det mer Geoguessr aktig.

2023-10-30 16:05 UTC, mrtz-j requested changes
Det over, ellers ser oppgaven bra ut.

2023-10-30 19:36 UTC, Loevland commented
> Det over, ellers ser oppgaven bra ut.

Mulig den ikke burde være 150p ja, tenkte du at den passa meir 50p eller 100p? Hvis vi har flere bilda av den samme plassen tror æ den blir en god del enklere, for e nån butikka man enkelt kan søke "bak" kamera. Kunne alternativt krevd GPS-posisjon for flagget, men da tror æ den blir litt for vanskelig til å være en lettere misc-oppgave?

2023-10-30 20:46 UTC, mrtz-j commented
Mhmm, ja slik den er nå ville jeg ha satt den til 50-100. Men tenkte at vi kanskje kunne ta bilder fra flere steder også består flagget av de delene.

2023-11-01 10:18 UTC, Loevland commented
Kan ta å legge inn noen flere bilder av forskjellige stedet 👍🏼 Evt hvis du har noen forslag til bilder/steder kan du også evt legge inn

2023-11-01 10:18 UTC, Loevland commented
Tar å justere ned poeng etter at oppgaven har litt flere bilder

2024-01-01 11:52 UTC, mrtz-j approved these changes
LGTM 🎆

2024-01-01 11:52 UTC, merged