Infiltration
Loevland/UiTHack24 pull request #71
Opened 2023-10-27 22:42 UTC by sdalv1k

Closes #61

2023-10-28 11:17 UTC, Loevland submitted a review, later dismissed
Oppdater README.md tabellen i root-mappa til repoet, så er den good 👍🏼

2023-10-28 11:21 UTC, Loevland requested changes
Legg til challenge-navn i tabellen i README.md i root-mappa til repoet, så er denne good

2023-10-28 20:59 UTC, Loevland requested changes

2023-10-28 20:59 UTC, Loevland commented on README.md
> +| | | Radiation shield :computer: | | Expired License :key: | | |
Ser ut som om du accidentally fjernet den ene challengen fra tablet
```suggestion
| | | Radiation shield :computer: | | Expired License :key: | Alienware :closed_lock_with_key: | |
```

2023-10-28 21:17 UTC, sdalv1k commented on README.md
> +| | | Radiation shield :computer: | | Expired License :key: | | |
Ja, ble accidently fjernet når jeg skulle merge README.md. Har fikset det nå.

2023-10-29 09:54 UTC, Loevland approved these changes
LGTM

2023-10-29 09:55 UTC, merged