3D Cipher
Loevland/UiTHack24 pull request #72
Opened 2023-10-31 20:25 UTC by sdalv1k

Closes #69

2023-11-01 10:21 UTC, Loevland commented
Link til ZIP fra README.md er broken (uploads mappa ligger i src/ , men README linker til uploads utenon src/ mappa).

Skal teste challengen når æ får tid

2023-11-01 16:52 UTC, Loevland requested changes
Nice oppgave! (Lærte at -1%4 != 3 i C etter en stund xD)

2023-11-01 16:52 UTC, Loevland commented on Crypto/3D_cipher/README.md
> +- [3D_cipher.zip](uploads/3D_cipher.zip)
Hvis Uploads-mappa skal ligge inni src/ mappa:
```suggestion
- [3D_cipher.zip](src/uploads/3D_cipher.zip)
```

2023-11-01 21:46 UTC, sdalv1k commented
> Nice oppgave! (Lærte at -1%4 != 3 i C etter en stund xD)

Takk! (Fungerer med (unsigned int)-1 😄). Vet ikke helt hvor vanskelig oppgaven var. Flagget kunne vært enkryptert den andre veien for å gjøre det litt vanskeligere.

2023-11-02 10:28 UTC, Loevland commented
Vil anslå 250-300 er sånn ca der den ligger nå. Flere kan prøve å løse den (som ikke vet løsningen) for å gi et bedre anslag på hvor vanskelig den er. Bare å la den stå på poengene den har nå, så retter vi heller i ettertid når vi har en gjennomgang av alle oppgavene

2023-11-04 20:20 UTC, Loevland approved these changes
LGTM

2023-11-04 20:20 UTC, merged