74 subpar encryption standard
Loevland/UiTHack24 pull request #89
Opened 2024-01-15 19:23 UTC by frapzo

Added an easy 50pts Crypto flag

2024-01-17 20:58 UTC, Loevland approved these changes

2024-01-17 20:59 UTC, Loevland requested changes
Oppdater README tabell i / , og så er denne good 👍🏼

2024-01-19 15:05 UTC, frapzo commented
har økt poengene til 80pts og endret vanskligheten til medium

2024-01-21 12:47 UTC, Loevland requested changes
Oppdater oppgaveoversikten i README.md i "/" på dette repoet, så er denne good

2024-01-21 14:02 UTC, frapzo commented
oppgaven er lagt til i README i root, men se over at merge conflicten ble håndtert riktig

2024-01-21 14:04 UTC, Loevland approved these changes

2024-01-21 14:04 UTC, merged