100 pts RevEng F#
Loevland/UiTHack24 pull request #93
Opened 2024-01-26 13:02 UTC by mrtz-j

Closes #50 ish

2024-01-27 18:51 UTC, Loevland requested changes
Oppgavetekst mangler

2024-01-29 15:04 UTC, mrtz-j commented
> Oppgavetekst mangler

Hehe, ja er fortsatt en draft. Litt usikker på vanskelighetsgraden.

2024-01-29 15:06 UTC, Loevland commented
Hvis vi kjøre dynamisk scoring av oppgavan treng vi ikke bekymre oss over scoring.

Skal deltageran få x86 versjonen av programmet, eller bare ARM versjonen?

2024-01-29 15:26 UTC, mrtz-j commented
Skal se om jeg får programmet litt mindre, så skal jeg compile det for x86-linux

2024-01-31 19:03 UTC, mrtz-j commented
> Oppgavetekst mangler

Har lagt til oppgavetekst nå og plasert linux binary'en i root.

2024-02-10 19:14 UTC, Loevland approved these changes
LGTM

2024-02-10 19:14 UTC, merged